# Generated by Django 3.0.3 on 2020-02-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('level_one', models.TextField()),
                ('level_two', models.TextField()),
                ('level_three', models.TextField()),
                ('price', models.TextField()),
                ('bid_price', models.TextField()),
                ('number', models.TextField()),
                ('property_fields', models.TextField()),
                ('joint_purchase', models.TextField()),
                ('unit', models.TextField()),
                ('picture', models.TextField()),
                ('display_onscreen', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
